on:
  workflow_dispatch:
jobs:
  build-and-run:
      runs-on: ubuntu-latest
      environment: Production
    
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build Docker Image and Push to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3
        with:
          github_token: ${{ github.token }}
          image_name: ${{ github.repository }}
          dockerfile-path: .
          context: .
